spring:
  datasource:
    url: jdbc:mysql://112.216.172.26:3306/mallstore_v35_new_kyochonfnb
    username: mallshoppingV35
    password: ahftmxhdj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    mapping-resources: META-INF/test.xml  
    
server:
  port: 8080